# typed: false
# frozen_string_literal: true

# This file was generated by scripts/homebrew-formula. DO NOT EDIT.
class Dayone2md < Formula
  desc "Export Day One to Markdown"
  homepage "https://github.com/kwo/dayone2md"
  version "1.2.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kwo/dayone2md/releases/download/v1.2.9/dayone2md_v1.2.9_darwin_arm64.tar.gz"
      sha256 "3948e641338d5aa4d0cdaa2ce2003a0c620fadad239bf504b2cdc32122536568"
    elsif Hardware::CPU.intel?
      url "https://github.com/kwo/dayone2md/releases/download/v1.2.9/dayone2md_v1.2.9_darwin_amd64.tar.gz"
      sha256 "bf2fb3483f86126ac13733874fa99f22da287b8da46b893602c038e2221c9e86"
    end
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm? || Hardware::CPU.intel?
        bin.install "dayone2md"
      else
        odie "dayone2md supports only macOS on amd64/arm64"
      end
    else
      odie "dayone2md supports only macOS on amd64/arm64"
    end
  end
end
