# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dayone2md < Formula
  desc ""
  homepage "https://github.com/kwo/homebrew-tools"
  version "1.2.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kwo/dayone2md/releases/download/v1.2.3/dayone2md_Darwin_arm64.tar.gz"
      sha256 "6510fda62d19da47a5b276c7f77234727f735d5310a358bab9cde03894b0c667"

      def install
        bin.install "dayone2md"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kwo/dayone2md/releases/download/v1.2.3/dayone2md_Darwin_x86_64.tar.gz"
      sha256 "392d09041971048b851e1a753df6cdea72a75ea904b5504b14a4692a5eda5cd2"

      def install
        bin.install "dayone2md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwo/dayone2md/releases/download/v1.2.3/dayone2md_Linux_arm64.tar.gz"
      sha256 "3a7cee2f60f68373740fe28ef24c87f00d73b5132b4dd04b77c90ce7e86df51f"

      def install
        bin.install "dayone2md"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kwo/dayone2md/releases/download/v1.2.3/dayone2md_Linux_x86_64.tar.gz"
      sha256 "816c8f80537b1e8598c1f3767fa7ddd6400dcf8e3a5c4ccb6fcc344b896afaa9"

      def install
        bin.install "dayone2md"
      end
    end
  end
end
