# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dayone2md < Formula
  desc ""
  homepage "https://github.com/kwo/homebrew-tools"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kwo/dayone2md/releases/download/v1.1.0/dayone2md_Darwin_arm64.tar.gz"
      sha256 "01431b5340434c5cff078ce78287bc7564f7381bf1d8545fc26260e79b1e4d3b"

      def install
        bin.install "dayone2md"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kwo/dayone2md/releases/download/v1.1.0/dayone2md_Darwin_x86_64.tar.gz"
      sha256 "17233b3abc9118498e9c061fdf1227630218c8b00b6e371efc5a465a1ec35694"

      def install
        bin.install "dayone2md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwo/dayone2md/releases/download/v1.1.0/dayone2md_Linux_arm64.tar.gz"
      sha256 "73d0f6b4d663cb1054a76a3aab44c06ce4f6bbcb94b5e67c8d76eb0dc8dc1de8"

      def install
        bin.install "dayone2md"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kwo/dayone2md/releases/download/v1.1.0/dayone2md_Linux_x86_64.tar.gz"
      sha256 "f97e5a9bf9f01d9fc216c996a9c194bb99adcb8e43b7a1cb11ecded228bfc0f3"

      def install
        bin.install "dayone2md"
      end
    end
  end
end
