# typed: false
# frozen_string_literal: true

# This file was generated by scripts/homebrew-formula. DO NOT EDIT.
class Gfa < Formula
  desc "Git Fetch All CLI for scanning and updating repos in bulk"
  homepage "https://github.com/kwo/gfa"
  url "https://github.com/kwo/gfa/releases/download/v1.2.0/gfa_v1.2.0.tar.gz"
  sha256 "5cc38ab833372bed3a74d58ec0ded66da1cb498d62c5e901aae605a64d329741"
  version "1.2.0"
  depends_on "node"

  def install
    bin.install "gfa"
  end
end
