# typed: false
# frozen_string_literal: true

# This file was generated by scripts/homebrew-formula. DO NOT EDIT.
class Gfa < Formula
  desc "Git Fetch All CLI for scanning and updating repos in bulk"
  homepage "https://github.com/kwo/gfa"
  version "1.0.0"
  depends_on "node"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kwo/gfa/releases/download/v1.0.0/gfa_v1.0.0_darwin_arm64.tar.gz"
      sha256 "6457c6ca100e2b231da4a5133d585a5a9b407ac50716dd3e1a0e51f7e68270f5"
    elsif Hardware::CPU.intel?
      url "https://github.com/kwo/gfa/releases/download/v1.0.0/gfa_v1.0.0_darwin_amd64.tar.gz"
      sha256 "7585827d01768cfca6a0d882aefe0bf22315f08e999077d75bd413465f67f5b3"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwo/gfa/releases/download/v1.0.0/gfa_v1.0.0_linux_arm64.tar.gz"
      sha256 "f698cc151d0f9ed5ce4c60ae42fda7715d78502ddc3a60502262b32deff284a6"
    elsif Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwo/gfa/releases/download/v1.0.0/gfa_v1.0.0_linux_amd64.tar.gz"
      sha256 "7585827d01768cfca6a0d882aefe0bf22315f08e999077d75bd413465f67f5b3"
    end
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm? || Hardware::CPU.intel?
        bin.install "gfa"
      else
        odie "gfa supports only macOS/Linux on amd64/arm64"
      end
    elsif OS.linux?
      if (Hardware::CPU.arm? || Hardware::CPU.intel?) && Hardware::CPU.is_64_bit?
        bin.install "gfa"
      else
        odie "gfa supports only macOS/Linux on amd64/arm64"
      end
    else
      odie "gfa supports only macOS/Linux on amd64/arm64"
    end
  end
end
