# typed: false
# frozen_string_literal: true

# This file was generated by scripts/homebrew-formula. DO NOT EDIT.
class Gfa < Formula
  desc "Git Fetch All CLI for scanning and updating repos in bulk"
  homepage "https://github.com/kwo/gfa"
  url "https://github.com/kwo/gfa/releases/download/v1.2.1/gfa_v1.2.1.tar.gz"
  sha256 "5aa51131ee5742c9ba9ba7454e29f45a59245946389eaf4ad087c70e6feaef52"
  version "1.2.1"
  depends_on "node"

  def install
    bin.install "gfa"
  end
end
