# typed: false
# frozen_string_literal: true

# This file was generated by scripts/homebrew-formula. DO NOT EDIT.
class Todolist < Formula
  desc "Local-first CLI for managing todos stored as Markdown files"
  homepage "https://github.com/kwo/todolist"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kwo/todolist/releases/download/v1.0.1/todolist_v1.0.1_darwin_arm64.tar.gz"
      sha256 "fc2fa1859d3ffbae6da63f90b147a5bdf62b4b06f1794026832a5ffd6c22d899"
    elsif Hardware::CPU.intel?
      url "https://github.com/kwo/todolist/releases/download/v1.0.1/todolist_v1.0.1_darwin_amd64.tar.gz"
      sha256 "00429e51ff33646ca094f96f962d4db8ececd608fd550ae5fbbfcd81b3169c72"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwo/todolist/releases/download/v1.0.1/todolist_v1.0.1_linux_arm64.tar.gz"
      sha256 "3ed5e3f9629dbc144ad1a252743da49b8ac84dff56bf4e46fcbf487eaf848e1e"
    elsif Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwo/todolist/releases/download/v1.0.1/todolist_v1.0.1_linux_amd64.tar.gz"
      sha256 "63eae8cc90aa8c0a106bf19c86196ce5e7bc279b75661af84cb4eec08d848832"
    end
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm? || Hardware::CPU.intel?
        bin.install "todolist"
      else
        odie "todolist supports only macOS/Linux on amd64/arm64"
      end
    elsif OS.linux?
      if (Hardware::CPU.arm? || Hardware::CPU.intel?) && Hardware::CPU.is_64_bit?
        bin.install "todolist"
      else
        odie "todolist supports only macOS/Linux on amd64/arm64"
      end
    else
      odie "todolist supports only macOS/Linux on amd64/arm64"
    end
  end
end
