# typed: false
# frozen_string_literal: true

# This file was generated by scripts/homebrew-formula. DO NOT EDIT.
class Todolist < Formula
  desc "Local-first CLI for managing todos stored as Markdown files"
  homepage "https://github.com/kwo/todolist"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kwo/todolist/releases/download/v1.0.2/todolist_v1.0.2_darwin_arm64.tar.gz"
      sha256 "77bb72363ad526891531f4c20a15ca99201ad2193c60544f5758f4511433fc94"
    elsif Hardware::CPU.intel?
      url "https://github.com/kwo/todolist/releases/download/v1.0.2/todolist_v1.0.2_darwin_amd64.tar.gz"
      sha256 "265f971d57fc85103c01196092f50e90b1fe3391096e5172478b5b47e6c1d14e"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwo/todolist/releases/download/v1.0.2/todolist_v1.0.2_linux_arm64.tar.gz"
      sha256 "a3e02ef98e12a8a28e02e54c231283a87717c83f0d926c8059101cfcd86944ab"
    elsif Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwo/todolist/releases/download/v1.0.2/todolist_v1.0.2_linux_amd64.tar.gz"
      sha256 "d3174bbb62cde7968d8a24b3e022eacb1a52238bcd0b735e989a5696cf13fa21"
    end
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm? || Hardware::CPU.intel?
        bin.install "todolist"
      else
        odie "todolist supports only macOS/Linux on amd64/arm64"
      end
    elsif OS.linux?
      if (Hardware::CPU.arm? || Hardware::CPU.intel?) && Hardware::CPU.is_64_bit?
        bin.install "todolist"
      else
        odie "todolist supports only macOS/Linux on amd64/arm64"
      end
    else
      odie "todolist supports only macOS/Linux on amd64/arm64"
    end
  end
end
