# typed: false
# frozen_string_literal: true

# This file was generated by scripts/homebrew-formula. DO NOT EDIT.
class Todolist < Formula
  desc "Local-first CLI for managing todos stored as Markdown files"
  homepage "https://github.com/kwo/todolist"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kwo/todolist/releases/download/v1.0.3/todolist_v1.0.3_darwin_arm64.tar.gz"
      sha256 "376ffbbb0140d4be1d46d8512f52d8e8901e8ab67dd15675f1062f8d80275f25"
    elsif Hardware::CPU.intel?
      url "https://github.com/kwo/todolist/releases/download/v1.0.3/todolist_v1.0.3_darwin_amd64.tar.gz"
      sha256 "37f1a5155ab988b6d896639ebc31674948ad5cce014eb9d2a0c218b8891e5a52"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwo/todolist/releases/download/v1.0.3/todolist_v1.0.3_linux_arm64.tar.gz"
      sha256 "ee3c5ff3b4241f9d37122a0383da21709acfba6e1fc5e621bd23fcdc6da8aaad"
    elsif Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwo/todolist/releases/download/v1.0.3/todolist_v1.0.3_linux_amd64.tar.gz"
      sha256 "21b04ea2d8e1b46644e6e1e39f400db5987cc08a8e9c048d5bb9dc19efdc5817"
    end
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm? || Hardware::CPU.intel?
        bin.install "todolist"
      else
        odie "todolist supports only macOS/Linux on amd64/arm64"
      end
    elsif OS.linux?
      if (Hardware::CPU.arm? || Hardware::CPU.intel?) && Hardware::CPU.is_64_bit?
        bin.install "todolist"
      else
        odie "todolist supports only macOS/Linux on amd64/arm64"
      end
    else
      odie "todolist supports only macOS/Linux on amd64/arm64"
    end
  end
end
