# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uts < Formula
  desc ""
  homepage "https://github.com/kwo/homebrew-tools"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kwo/uts/releases/download/v1.1.1/uts_Darwin_x86_64.tar.gz"
      sha256 "690749a907bcb4c60fe5b963515cdf46a61ca49187a51cee7e696da2c03cc9fa"

      def install
        bin.install "uts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kwo/uts/releases/download/v1.1.1/uts_Darwin_arm64.tar.gz"
      sha256 "d00507506e055c42578707bc01f27698db685a86d316c6b31b922e819582aa24"

      def install
        bin.install "uts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kwo/uts/releases/download/v1.1.1/uts_Linux_x86_64.tar.gz"
      sha256 "295690bec6029abd91ec84a904a4b53c1a4e86d80a5415dc8ff59e14a07efef0"

      def install
        bin.install "uts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwo/uts/releases/download/v1.1.1/uts_Linux_arm64.tar.gz"
      sha256 "1fe1753c6283db216049546f49ed02e8ce4b3ea66ea1d0210938e6eba9b777b8"

      def install
        bin.install "uts"
      end
    end
  end
end
