# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uts < Formula
  desc ""
  homepage "https://github.com/kwo/homebrew-tools"
  version "1.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kwo/uts/releases/download/v1.1.2/uts_Darwin_arm64.tar.gz"
      sha256 "e3743a14a8584f0df928ff4d77675ec55541e79864c65d8e9c5246e7059ceac5"

      def install
        bin.install "uts"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kwo/uts/releases/download/v1.1.2/uts_Darwin_x86_64.tar.gz"
      sha256 "3e3fbd49d6027d729640a9beb246cac839e9bc11143b1c46f1274aef5e3ff78b"

      def install
        bin.install "uts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwo/uts/releases/download/v1.1.2/uts_Linux_arm64.tar.gz"
      sha256 "37af09fca71ac39a6d969c01740ee637341f0bcaef98954c752ce954417a3bd2"

      def install
        bin.install "uts"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kwo/uts/releases/download/v1.1.2/uts_Linux_x86_64.tar.gz"
      sha256 "fe5dfd2b7e82a723a5b5f5fbc7a79ba6763d32350b86450dadd7d36d4b206fc2"

      def install
        bin.install "uts"
      end
    end
  end
end
